[workspace]
members = [
    "hf-hub", "hf-model-downloader",
]

resolver = "2"


[workspace.dependencies]
serde_json = "1.0"
candle-core = "0.4.0"
hf-hub = "0.3.2"
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }